[package]
name = "roons"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.dev.package.'*']
opt-level = 3
debug = false
